CREATE DATABASE takos;

CREATE TABLE IF NOT EXISTS usuarios(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL UNIQUE,
    nombre text,
    primerapregunta text,
    primerapreguntarespuesta text,
    segundapregunta text,
    segundapreguntarespuesta text,
    admin boolean,
    clave text
);  


CREATE TABLE IF NOT EXISTS usuariosimagenes(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    path text,
    usuarioid integer REFERENCES usuarios(id) 
);

CREATE TABLE IF NOT EXISTS pelajes(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text
);

CREATE TABLE IF NOT EXISTS logros(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text
);

CREATE TABLE IF NOT EXISTS hierros(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    path text,
    codigo text
);

INSERT INTO logros ( nombre ) Values ( '1 oreja');
INSERT INTO logros ( nombre ) Values ( '2 orejas');
INSERT INTO logros ( nombre ) Values ( '2 orejas y colas');
INSERT INTO logros ( nombre ) Values ( 'Indulto');

INSERT INTO usuarios ( email , nombre, primerapregunta , primerapreguntarespuesta , segundapregunta, segundapreguntarespuesta, clave ) Values ( 'admin' , 'admin' , 'admin' , 'admin' , 'admin' , 'admin' , true , 'admin' );

CREATE TABLE IF NOT EXISTS toros(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text,
    hierro text,
    hierrocodigo text,
    pelaje integer REFERENCES pelajes(id),
    sexo text,
    fechanac text,
    encaste text,
    madreid integer,
    padreid integer,
    tatuaje text,
    tientaDia text,
    tientaResultado text,
    tientaTentadoPor text,
    tientaLugar text,
    tientaCapa text,
    tientaCaballo text,
    tientaMuleta text
);

CREATE TABLE IF NOT EXISTS torosimagenes(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    path text,
    torosid integer REFERENCES toros(id) 
);